services:
  native-app-db:
    image: postgres:15
    container_name: native-app
    environment:
      POSTGRES_USER: teuzo
      POSTGRES_PASSWORD: teuzo123
      POSTGRES_DB: native-app
    ports:
      - "5432:5432"
    volumes:
      - native-app-data:/var/lib/postgresql/data

volumes:
  native-app-data:
cd backend
